### PR TITLE
Reordered logic to prevent eslint no-unsafe-optional-chaining error

### PR DESCRIPTION
**Pull request by Nexidian**
A fresh clone and install of this repo presents the following error

image

This is due to optional chaining not being allowed within a for loop on an array. An attempt has been made to suppress this with

```js
 /*eslint no-unsafe-optional-chaining: "error"*/
for (let method of contract?.abi) {
```
But the suppression line should be 

```js
// eslint-disable-next-line no-unsafe-optional-chaining
```

However, we don't need to suppress this error. Moving the options initialisation above this call will allow us to use `options.abi` instead of `contract?.abi`. This way `options.abi` will be set to `undefined` if it doesn't exist, meaning the for loop never executes.

### CODE REVIEW

**Review by jcrooke — APPROVED** [review]

**Comment by Nexidian** [comment]
@Y0moo  can I get your eyes on this one please

**Comment by Nexidian** [comment]
@Y0moo bump

**Comment by Nexidian** [comment]
@ivan-liljeqvist @Y0moo Any chance we can get this merged please. It's will prevent further issues being raised and does currently break for new installs

**Review by coderdidit — APPROVED** [review]
it will be great to merge this

**Pull request closed without merging**
